#include "http_response.h"
#include <stdio.h>
#include <stdlib.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>
#include <string.h>


void test()
{
    http_request req;
    req.raw_request = "GET / HTTP/1.1\r\nHost: www.example.com\r\nUser-Agent: MyCustomClient/1.0\r\nAccept: text/html\r\n\r\n\0";
    req.request_len = strlen(req.raw_request);
    int err_code = 0;
    parse_request(&req, &err_code);
    print_request_info(&req);
    http_response res;
    build_http_response(&res,&req,&err_code);
    print_response_info(&res);
}

int send_all(int clientSocket, const char* buf, size_t buf_len)
{
    const char* ptr = buf;
    ssize_t remaining = buf_len;
    while(remaining > 0)
    {
        ssize_t sent = send(clientSocket, ptr, remaining, 0);
        if(sent<0)
        {
            return -1;
        }
        ptr += sent;
        remaining -= sent;
    }
    return 0;
}

int send_http_response(int client_fd, http_response* res)
{
    if(send_all(client_fd, res->response_head, res->response_head_len) < 0)
        return -1;

    if(res->body_file)
    {
        char buf[SEND_BUF_SIZE];
        size_t bytes_read;
        while((bytes_read = fread(buf, 1, sizeof buf, res->body_file)) > 0)
        {
            if(send_all(client_fd, buf, bytes_read) < 0)
                return -1;

        }
        fclose(res->body_file);
    }
    return 0;
}

int main()
{

    // Useful reference for these functions: https://pubs.opengroup.org/onlinepubs/9799919799/
    // AF_INET for IPv4, SOCK_STREAM for socket type (used for TCP), 0for default protocol of for the requested socket type, in this case TCP
    int serverSocket = socket(AF_INET, SOCK_STREAM, 0);
    if (serverSocket == -1)
    {
        // Can use errno to get more specific errors
        return 1;
    }

    struct sockaddr_in serverAddr = {0};
    serverAddr.sin_family = AF_INET;
    // htons converts from little-endian (how computers store multi-byte values) to big-endian (how network protocols store multi-byte values)
    serverAddr.sin_port = htons(8080);
    // INADDR_ANY means that we accept connection on all local network interfaces
    serverAddr.sin_addr.s_addr = INADDR_ANY;


    int opt = 1;
    setsockopt(serverSocket, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    // Associates a socket with an IP address and port number
    if (bind(serverSocket, (struct sockaddr *)&serverAddr, sizeof(serverAddr)) == -1)
    {
        // Can use errno to get more specific errors
        return 1;
    }

    // listen() tells OS to start listening for connection request on the given socket, second parameter is maximum number of pending connections the queue can hold
    if (listen(serverSocket, 5) == -1)
    {
        // Can use errno to get last error which correspond to specific errors
        return 1;
    }

    // accept() takes the connection request from the front of the queue generated by listen().
    // The OS creates another socket with the same socket type(SOCK_STREAM), protocol(TCP) and address family(IPv4). Returns the file descriptor.
    int clientSocket = accept(serverSocket, NULL, NULL);
    if (clientSocket == -1)
    {
        // Can use errno to get more specific errors
        return 1;
    }

    printf("Received Connection starting communication now \n");
    char buffer[1024];
    while(1)
    {
        ssize_t byteSize = recv(clientSocket, buffer, sizeof(buffer) - 1, 0);
        if(byteSize > 0)
        {
            buffer[byteSize] = '\0';
            http_request req;
            req.raw_request = buffer;
            req.request_len = strlen(buffer);
            int err_code = 0;
            parse_request(&req, &err_code);
            print_request_info(&req);
            http_response res;
            build_http_response(&res,&req,&err_code);
            print_response_info(&res);
            send_http_response(clientSocket, &res);
        }
        else if(byteSize == 0)
        {
            printf("Client Disconnected \n");
            break;
        }
        else
        {
            printf("Error in receiving transmission from client \n");
            break;
        }
    }

    return 0;
}
